packages:
  - "playground"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: false
  unrs-resolver: false

overrides:
  "@nuxt/kit": "^4.0.0"
  "@nuxt/schema": "4.1.1"
  nuxt-workers: "link:."
